# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Price(models.Model):
   date = models.DateField()
   symbol = models.CharField(max_length=5)
   open = models.FloatField()
   close = models.FloatField()
   low = models.FloatField()
   high = models.FloatField()
   volume = models.FloatField()

class Fundemental(models.Model):
    symbol = models.CharField(max_length=5)
    period_ending = models.DateField()
    accounts_payable = models.FloatField()
    accounts_receivable = models.FloatField()
    addl_income_expense_items = models.FloatField()
    after_tax_roe = models.FloatField()
    capital_expenditures = models.FloatField()
    capital_surplus = models.FloatField()
    cash_ratio = models.FloatField()
    cash_and_equivalents = models.FloatField()
    inventory_changes = models.FloatField()
    common_stocks = models.FloatField()
    cost_of_revenue = models.FloatField()
    current_ratio = models.FloatField()
    deferred_asset_charges = models.FloatField()
    deferred_liability_charges = models.FloatField()
    depreciation = models.FloatField()
    earnings_before_interest = models.FloatField()
    earnings_before_tax = models.FloatField()
    effect_of_exchange_rate = models.FloatField()
    equity_earnings_or_loss = models.FloatField()
    fixed_assets = models.FloatField()
    goodwill = models.FloatField()
    gross_margin = models.FloatField()
    gross_profit = models.FloatField()
    income_tax = models.FloatField()
    intangible_assets = models.FloatField()
    interest_expense = models.FloatField()
    inventory = models.FloatField()
    investments = models.FloatField()
    liabilities = models.FloatField()
    long_term_debt = models.FloatField()
    long_term_investments = models.FloatField()
    minority_interest = models.FloatField()
    misc_stocks = models.FloatField()
    net_borrowings = models.FloatField()
    net_cash_flow = models.FloatField()
    net_cash_flow_operating = models.FloatField()
    net_cash_flows_financing = models.FloatField()
    net_cash_flows_investing = models.FloatField()
    net_income = models.FloatField()
    net_income_adjustments = models.FloatField()
    net_applicable_income = models.FloatField()
    net_continuous_income = models.FloatField()
    net_receivables = models.FloatField()
    non_recurring_items = models.FloatField()
    operating_income = models.FloatField()
    operating_margin = models.FloatField()
    other_assets = models.FloatField()
    other_current_liabilities = models.FloatField()
    other_equity = models.FloatField()
    other_financing_activities = models.FloatField()
    other_investing_activities = models.FloatField()
    other_liabilities = models.FloatField()
    other_operating_activities = models.FloatField()
    other_operating_items = models.FloatField()
    pre_tax_margin = models.FloatField()
    pre_tax_roe = models.FloatField()
    profit_margin = models.FloatField()
    quick_ratio = models.FloatField()
    research_and_development = models.FloatField()
    retained_earnings = models.FloatField()
    sale_and_purchase_of_stock = models.FloatField()
    sales_general_and_admin = models.FloatField()
    short_term_to_long_term_debt = models.FloatField()
    short_term_investments = models.FloatField()
    total_assets = models.FloatField()
    total_current_assets = models.FloatField()
    total_current_liabilities = models.FloatField()
    total_equity = models.FloatField()
    total_liabilities = models.FloatField()
    total_liabilities_and_equity = models.FloatField()
    total_revenue = models.FloatField()
    treasury_stock = models.FloatField()
    for_year = models.FloatField()
    earnings_per_share = models.FloatField()
    estimated_shares_outstanding = models.FloatField()

class Security(models.Model):
    symbol = models.CharField(max_length=5)
    name = models.CharField(max_length=30)
    sec_filings = models.CharField(max_length=30)
    gics_sector = models.CharField(max_length=30)
    gics_sub_industry = models.CharField(max_length=30)
    address = models.CharField(max_length=30)
    date_added = models.DateField()
    cik = models.IntegerField()

class Company(models.Model):
    symbol = models.CharField(max_length=5)
